ALTER TABLE job_parts ALTER COLUMN part_id DROP NOT NULL;
ALTER TABLE job_parts ADD COLUMN IF NOT EXISTS is_custom BOOLEAN DEFAULT FALSE;
ALTER TABLE job_parts ADD COLUMN IF NOT EXISTS custom_name TEXT;
ALTER TABLE job_parts ADD COLUMN IF NOT EXISTS cost_at_time_lkr NUMERIC DEFAULT 0;
